name: akropolis
description: "A video based social media app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner:
  build_runner:

flutter_gen:
  output: lib/gen/
  line_length: 80

  assets:
    outputs:
      package_parameter_enabled: false
      directory_path_enabled: true
      parse_metadata: true

  fonts:
    outputs:
      package_parameter_enabled: false

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true
  assets:
   - assets/

  fonts:
   - family: Jersey10
     fonts:
        - asset: fonts/Jersey10-Regular.ttf
   - family: Inter
     fonts:
       - asset: fonts/Inter_18pt-Medium.ttf
