name: akropolis
description: "A video based social media app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.10.1
  freezed: ^2.5.7
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  fluttertoast: ^8.2.10
  firebase_storage:
  google_sign_in:
  get_it:
  network_service:
    git:
      url: https://bruc3balo:glpat-45CSRAxm48QD31nbADxz@gitlab.com/flutter_starter/network_service.git
      ref: main
  logging_service:
    git:
      url: https://bruc3balo:glpat-45CSRAxm48QD31nbADxz@gitlab.com/flutter_starter/logging_service.git
      ref: main
  common_fn:
    git:
      url: https://bruc3balo:glpat-45CSRAxm48QD31nbADxz@gitlab.com/flutter_starter/common_fn.git
      ref: main
  paged_list_view:
    git:
      url: https://bruc3balo:glpat-45CSRAxm48QD31nbADxz@gitlab.com/flutter_starter/paged_list_view.git
      ref: main
  exception_base:
    git:
      url: https://bruc3balo:glpat-45CSRAxm48QD31nbADxz@gitlab.com/flutter_starter/exception_base.git
      ref: main
  camera: ^0.11.1
  video_player:
  chewie:
  path_provider:
  image_picker: ^1.1.2
  get_thumbnail_video: ^0.7.3
  loading_animation_widget:
  dio:
  ffmpeg_kit_flutter_full_gpl:
    path: ../ffmpeg_kit_flutter_full_gpl-6.0.3
  cached_network_image: ^3.3.1
  flutter_cache_manager:
  intl:
  infinite_carousel: ^1.1.1
  dots_indicator: ^4.0.0
  hive: ^2.2.3
  flutter_secure_storage: ^9.2.4
  #ffmpeg_helper: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner:
  build_runner:
  json_serializable:
  hive_generator:


flutter_gen:
  output: lib/domain/gen/
  line_length: 80

  assets:
    outputs:
      package_parameter_enabled: false
      directory_path_enabled: true
      parse_metadata: true

  fonts:
    outputs:
      package_parameter_enabled: false

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true
  assets:
   - assets/

  fonts:
   - family: Jersey10
     fonts:
        - asset: fonts/Jersey10-Regular.ttf
   - family: Inter
     fonts:
       - asset: fonts/Inter_18pt-Medium.ttf
